import type { ShopGroupSlug } from "./catalog";

const bucket = "tenderpro-480721.firebasestorage.app";

function productPhoto(file: string) {
  return `https://storage.googleapis.com/${bucket}/products/v3/${file}`;
}

export const groupImage: Record<ShopGroupSlug, string> = {
  "business-cards": productPhoto("business-cards.jpg"),
  "flyers-posters": productPhoto("flyers.jpg"),
  banners: productPhoto("rollup.jpg"),
  events: productPhoto("teardrop.jpg"),
  apparel: productPhoto("tshirt.jpg"),
  "mugs-promo": productPhoto("mug.jpg"),
  "stickers-signage": productPhoto("stickers.jpg"),
  stationery: productPhoto("letterhead.jpg"),
  "packaging-photo": productPhoto("kraft-bag.jpg"),
};

const photoBySlug: Record<string, string> = {
  "business-cards-printing": "business-cards.jpg",
  "spot-uv-business-cards": "spot-uv-cards.jpg",
  "bookmarks-printing": "bookmarks.jpg",
  "postcards-printing": "postcards.jpg",
  "gift-voucher-printing": "voucher.jpg",
  "flyers-printing": "flyers.jpg",
  "brochure-printing": "brochure.jpg",
  "posters-printing": "poster.jpg",
  "architectural-blueprints": "blueprint.jpg",
  "x-banner-printing": "x-banner.jpg",
  "roll-up-banner-printing": "rollup.jpg",
  "banner-printing": "banner.jpg",
  "wheel-cover-printing": "wheel-cover.jpg",
  "door-frame-banner-printing": "door-banner.jpg",
  "tear-drop-banner-printing": "teardrop.jpg",
  "adjustable-backdrop-banner-printing": "backdrop.jpg",
  "telescopic-banners-printing": "telescopic.jpg",
  "popup-banner-printing": "popup.jpg",
  "s-banner-printing": "s-banner.jpg",
  "l-banner-stand": "l-banner.jpg",
  "table-rollup-printing": "table-rollup.jpg",
  "media-wall-banner": "media-wall.jpg",
  "brochure-stand": "brochure-stand.jpg",
  "2026-calendar-printing": "calendar.jpg",
  "custom-flag-printing": "flag.jpg",
  nametags: "nametag.jpg",
  "umbrella-printing": "umbrella.jpg",
  "kitenge-notebooks": "kitenge-notebook.jpg",
  "selfie-frames": "selfie-frame.jpg",
  "tent-cards-printing": "tent-card.jpg",
  "table-cloth-printing": "tablecloth.jpg",
  "branded-wristbands": "wristband.jpg",
  "button-badges-printing": "badge.jpg",
  "branded-t-shirt": "tshirt.jpg",
  "round-neck-plain-t-shirt": "plain-tshirt.jpg",
  "reflector-jackets-printing": "reflector.jpg",
  "branded-jerseys-for-clubs": "jersey.jpg",
  "branded-hoodies": "hoodie.jpg",
  "branded-aprons": "apron.jpg",
  "branded-enamel-mugs": "enamel-mug.jpg",
  "branded-drawstring-bags": "drawstring.jpg",
  "branded-mugs": "mug.jpg",
  "notebook-printing": "notebook.jpg",
  "mouse-pads-printing": "mousepad.jpg",
  "branded-pens": "pen.jpg",
  "branded-keyholders": "keyholder.jpg",
  "branded-tote-bags": "tote.jpg",
  "branded-long-mousepad": "long-mousepad.jpg",
  "branded-caps": "cap.jpg",
  "car-magnets-printing": "car-magnet.jpg",
  "skin-feel-thermal-flask-printing": "flask.jpg",
  "thermal-travel-mugs": "travel-mug.jpg",
  "branded-water-bottles": "bottle.jpg",
  "vinyl-sticker-printing": "stickers.jpg",
  "reflective-sticker-printing": "reflective-sticker.jpg",
  "adhesive-label-stickers-printing": "labels.jpg",
  "floor-stickers-printing": "floor-sticker.jpg",
  "car-stickers-printing-in-kenya": "car-sticker.jpg",
  "rigid-sign-boards-printing": "sign.jpg",
  "3d-signs": "sign-3d.jpg",
  "door-plates": "door-plate.jpg",
  "envelopes-printing": "envelope.jpg",
  "new-baby-cards": "baby-card.jpg",
  "certificates-printing": "certificate.jpg",
  "menu-printing": "menu.jpg",
  "booklet-magazines-printing": "booklet.jpg",
  "letterheads-printing": "letterhead.jpg",
  "receipt-books-printing": "receipt-book.jpg",
  "wedding-cards-printing": "wedding-card.jpg",
  "spiral-binding-services": "spiral.jpg",
  "funeral-programs-printing": "funeral.jpg",
  "presentation-folders-printing": "folder.jpg",
  "book-printing": "book.jpg",
  "branded-2027-diary": "diary.jpg",
  "branded-journals-and-planners": "journal.jpg",
  "mounted-photos-printing": "mounted-photo.jpg",
  "photo-framing": "frame.jpg",
  "branded-jute-bags": "jute.jpg",
  "graphic-design-service": "design.jpg",
  "canvas-printing": "canvas.jpg",
  "packaging-boxes": "box.jpg",
  "document-printing": "documents.jpg",
  "branded-kraft-bags": "kraft-bag.jpg",
  "photo-printing-services": "photo-print.jpg",
};

export function productImage(product: { slug: string; group: ShopGroupSlug }) {
  const file = photoBySlug[product.slug];
  return file ? productPhoto(file) : groupImage[product.group];
}
